version: '3'

networks:
  nuxt-network:
    driver: bridge
  default:


volumes:
  public-storage:
  node_modules: {}

services:
  aue_frontend:
    build:
      dockerfile: ../docker/nuxt/Dockerfile
      context: './../frontend'
      args:
        - BASE_URL=https://buycardubai.com
        - API_URL=https://buycardubai.com/api
        - BACK_URL=https://buycardubai.com
    image: nginx:latest
    environment:
      - HOST=0.0.0.0
      - PORT=80
    restart: "no"
    ports:
      - "24680:24678"
      - "5000:80"
      - "445:443"
    volumes: 
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      # - /etc/nginx/sites-available/buycardubai:/etc/nginx/conf.d/default.conf
    networks:
      - nuxt-network
      - default
