version: '3'

networks:
  nuxt-network:
    driver: bridge
  default:


volumes:
  public-storage:
  node_modules: {}

services:
  rentcaruae_frontend:
    build:
      dockerfile: ../docker/nuxt/Dockerfile
      context: './../frontend'
      args:
        - BASE_URL=https://rentcaruae.com
        - API_URL=https://rentcaruae.com/api
        - BACK_URL=https://rentcaruae.com
    image: nginx:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    restart: "unless-stopped"
    ports:
      - "24681:24678"
      - "5002:3000"
    networks:
      - nuxt-network
      - default
